## INITIALIZE
genome:
    fa: "GRCh38.primary_assembly.genome.fa"
    size: "genome.size"
    fai: "GRCh38.primary_assembly.genome.fa.fai"
    blacklist: "hg38-blacklist.v2.bed"
    filtered_fai: "GRCh38.primary_assembly_filtered.genome.fa.fai"
    bed: "GRCh38.primary_assembly_filtered.bed"
    dhs: "DHS_hg38.bed"

annot:
    gtf: "gencode.v37.annotation.gtf.gz"
    bed: "GCA_000001405.15_GRCh38_full_analysis_set.refseq_annotation.bed"
    bw: "hg38.phastCons100way.bw"
    refseq_bed: "hg38_RefSeq.bed"
    housekeeping_bed: "hg38.HouseKeepingGenes.bed"
    lib: "ctat_genome_lib_build_dir"

## INGEST
input:
    input_fastq: "{{sample}}_{read}.fastq.gz"
    input_bam: "{sample}_input.bam"
cutadapt:
    cutadapt_fastq: "{{sample}}_{read}"
rqual_filter:
    qfilter_fastq_single: "{{sample}}_{read}_qual.fastq.gz"
    qfilter_fastq_paired: "{{sample}}_{read}{paired}_qual.fastq.gz"

## CONTAMINATION
centrifuge:
    classification: "{sample}_classification.txt"
    report: "{sample}_report.txt"
    tar: "p_compressed+h+v.tar.gz"
    db: "p_compressed+h+v.1.cf"

## MAPPING
bam:
    bam: "{sample}.bam"
    index: "{sample}.bam.bai"
    bam_transcriptome: "{sample}.Aligned.toTranscriptome.out.bam"
    chimeric_junction: "{sample}.Chimeric.out.junction"
    dup_bam: "{sample}_dup.bam"
    flags_bam: "{sample}_flags.bam"
    blacklist_bam: "{sample}_blacklist.bam"
    fixmate_bam: "{sample}_fixmate.bam"
    filtered_bam: "{sample}_filtered.bam"
    filtered_index: "{sample}_filtered.bam.bai"
    metrics: "{sample}_marked_duplicates_metrics.txt"
    sampled_bam: "{sample}_sampled.bam"
    sampled_index: "{sample}_sampled.bam.bai"
    stats: "{sample}_sorted_bam_stats.txt"
    size: "{sample}_bam_size.txt"
    downsampled_bam: "{sample}_downsampling.bam"
    downsampled_bai: "{sample}_downsampling.bam.bai"
    housekeeping_bam: "{sample}_housekeeping.bam"
    housekeeping_bai: "{sample}_housekeeping.bam.bai"

rseqc:
    bamqc_txt: "{sample}_bam_qc.txt"
    bamgc_txt: "{sample}_bam_gc.txt"
    bamgc_r: "{sample}.GC_plot.r"
    ts_txt: "tin_score/{sample}_downsampling.summary.txt"
    ts_xls: "tin_score/{sample}_downsampling.tin.xls"
    ts_txt_hk: "tin_score/{sample}_housekeeping.summary.txt"
    ts_xls_hk: "tin_score/{sample}_housekeeping.tin.xls"
    rd_txt: "read_distribution/{sample}_read_distrib.txt"
    gbc_png: "gene_body_coverage/{sample}.geneBodyCoverage.curves.png"
    gbc_r: "gene_body_coverage/{sample}.geneBodyCoverage.r"
    gbc_txt: "gene_body_coverage/{sample}.geneBodyCoverage.txt"
    js_plot: "junction_saturation/{sample}.junctionSaturation_plot.pdf"
    js_r: "junction_saturation/{sample}.junctionSaturation_plot.r"
    is_txt: "insert_size/{sample}_insert_size_metrics.txt"
    is_pdf: "insert_size/{sample}_insert_size_histogram.pdf"

fastqc:
    targz: "{sample}_filtered_fastqc.tar.gz"

fusion:
    tsv: "{sample}/{sample}.fusion_predictions.tsv"
    tsv_abridged: "{sample}/{sample}.fusion_predictions.abridged.tsv"
    tsv_sample: "{sample}/{sample}.fusion_predictions.abridged_addSample.tsv"

msisensor2:
    models: "models_hg38"
    output: "{sample}_msisensor2"
    txt: "{sample}_msisensor2.txt"
    dis: "{sample}_msisensor2_dis"
    somatic: "{sample}_msisensor2_somatic"
        
trust4:
    bcrtcr: "hg38_bcrtcr.fa"
    imgt: "human_IMGT+C.fa"
    cdr3: "{sample}/{sample}_cdr3.out"
    txt: "{sample}/{sample}_cdr3.out.processed.txt"
