## INITIALIZE
ref_files:
    fa: "GRCh38.primary_assembly.genome.fa"
    fai: "GRCh38.primary_assembly.genome.fa.fai"
    gtf: "gencode.v37.annotation.gtf"
    comp_bed: "gencode.v37.comprehensive.bed"
    housekeeping_bed: "gencode.v37.housekeeping_genes.bed"
    tar: "p_compressed+h+v.tar.gz"
    idx: "p_compressed+h+v.3.cf"
    models: "models_hg38"
    bcrtcr: "hg38_bcrtcr.fa"
    imgt: "human_IMGT+C.fa"
    lib: "ctat_genome_lib_build_dir"
    transcripts: "gencode.v37.transcripts.fa"

## INGEST
input:
    input_fastq: "{{sample}}_{read}.fastq.gz"
    input_bam: "{sample}_input.bam"
cutadapt:
    cutadapt_fastq: "{{sample}}_{read}"
rqual_filter:
    qfilter_fastq_single: "{{sample}}_{read}_qual.fastq.gz"
    qfilter_fastq_paired: "{{sample}}_{read}{paired}_qual.fastq.gz"

## MICROBIOME
centrifuge:
    txt: "{sample}_classification.txt"
    gz: "{sample}_classification.txt.gz"
    tsv: "{sample}_centrifuge_report.tsv"
    tsv_sample: "{sample}_centrifuge_addSample_report.tsv"

## MAPPING
bam:
    bam: "{sample}.bam"
    index: "{sample}.bam.bai"
    bam_transcriptome: "{sample}.Aligned.toTranscriptome.out.bam"
    chimeric_junction: "{sample}.Chimeric.out.junction"
    stats: "{sample}_sorted_bam_stats.txt"
    size: "{sample}_bam_size.txt"
    downsampled_bam: "{sample}_downsampling.bam"
    downsampled_bai: "{sample}_downsampling.bam.bai"
    housekeeping_bam: "{sample}_housekeeping.bam"
    housekeeping_bai: "{sample}_housekeeping.bam.bai"

## QC
rseqc:
    stat_txt: "bam_stat/{sample}_bam_stat.txt"
    gc_txt: "read_gc/{sample}_read_gc.txt"
    gc_r: "read_gc/{sample}.GC_plot.r"
    ts_txt: "tin_score/{sample}_downsampling.summary.txt"
    ts_xls: "tin_score/{sample}_downsampling.tin.xls"
    ts_txt_hk: "tin_score/{sample}_housekeeping.summary.txt"
    ts_xls_hk: "tin_score/{sample}_housekeeping.tin.xls"
    rd_txt: "read_distribution/{sample}_read_distrib.txt"
    gbc_png: "gene_body_coverage/{sample}.geneBodyCoverage.curves.png"
    gbc_r: "gene_body_coverage/{sample}.geneBodyCoverage.r"
    gbc_txt: "gene_body_coverage/{sample}.geneBodyCoverage.txt"
    js_plot: "junction_saturation/{sample}.junctionSaturation_plot.pdf"
    js_r: "junction_saturation/{sample}.junctionSaturation_plot.r"
    is_txt: "insert_size/{sample}_insert_size_metrics.txt"
    is_pdf: "insert_size/{sample}_insert_size_histogram.pdf"
    log: "gene_body_coverage/log.txt"

## FUSION
fusion:
    tsv: "{sample}/{sample}.fusion_predictions.tsv"
    tsv_abridged: "{sample}/{sample}.fusion_predictions.abridged.tsv"
    tsv_sample: "{sample}/{sample}.fusion_predictions.abridged_addSample.tsv"

## IMMUNE RESPONSE
msisensor2:
    output: "{sample}_msisensor2"
    txt: "{sample}_msisensor2.txt"
    dis: "{sample}_msisensor2_dis"
    somatic: "{sample}_msisensor2_somatic"

## IMMUNE REPERTOIRE
trust4:
    cdr3: "{sample}/{sample}_cdr3.out"
    txt: "{sample}/{sample}_cdr3.out.processed.txt"

## QUANTIFICATION
salmon:
    sf: "{sample}/{sample}_quant.sf"

## NEOANTIGEN
arcashla:
    fq1: "{sample}/{sample}.extracted.1.fq.gz"
    fq2: "{sample}/{sample}.extracted.2.fq.gz"
    p: "{sample}/{sample}.alignment.p"
    json_genes: "{sample}/{sample}.genes.json"
    json_genotype: "{sample}/{sample}.genotype.json"
    log: "{sample}/{sample}.genotype.log"
    merge: "merge/{sample}.genotype.json"

multiqc:
    html: "multiqc_report.html"
